# Generated by Django 4.0.3 on 2022-12-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0003_hats_alter_locationvo_closet_name_delete_hat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hats',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hats',
            name='name',
        ),
        migrations.AddField(
            model_name='hats',
            name='picture_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='hats',
            name='color',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hats',
            name='fabric',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hats',
            name='style_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='locationvo',
            name='closet_name',
            field=models.CharField(max_length=100),
        ),
    ]
