# Generated by Django 4.0.3 on 2022-12-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_alter_shoe_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='picture',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_url',
            field=models.URLField(null=True),
        ),
    ]
