# Generated by Django 4.0.3 on 2022-12-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0003_alter_shoe_picture_alter_shoe_shoe_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='shoe_url',
        ),
    ]
